# Generated by Django 4.2.5 on 2023-12-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_productparameter_unique_product_parameter_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productparameter',
            name='unique_product_parameter',
        ),
        migrations.AddConstraint(
            model_name='productparameter',
            constraint=models.UniqueConstraint(fields=('value', 'parameter', 'product_info'), name='unique_product_parameter'),
        ),
    ]
