# Generated by Django 4.2.5 on 2024-01-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_productparameter_unique_product_parameter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
