# Generated by Django 4.2.5 on 2024-01-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_productinfo_image_remove_productinfo_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinfo',
            name='price',
        ),
        migrations.AddField(
            model_name='productparameter',
            name='price',
            field=models.PositiveIntegerField(null=True, verbose_name='цена за 1пог.м/1шт'),
        ),
    ]
